### PR TITLE
APi

### PR DESCRIPTION
**Pull request by filoor**
Added to use the api with a apit key insteda off the sigin process

Handy if you want to use lets say "Tasker" for Android

### CODE REVIEW

**Comment by matteocargnelutti** [comment]
Hi Filoor,

Thank you for your contribution !

**There are serveral important problems with your proposal :** 
1. It is not clear what this api key parameter is made for
2. It is not clear what format this api key should have, nor what encryption / generation technique it should use
3. You have hard-coded a default value for this api key
4. The methods you added in the web controller would allow users to change that said api key without being logged-in and without checking the input.
5. The methods you added in the web controller won't work, as there are mixed-up variables names _(api given as function parameter, api_key used a few lines later)_
6. The methods you added in the web controller are not properly commented
7. The functionality your propose doesn't come with the appropriate unit tests

Thanks again,

**Comment by filoor** [comment]
Hi Maateo,

Thank you for your replay.
I just starting with python.

1. I use this method to use Connect with 3 party app 
   as for now i use is with tasker (see link cant add video)
[https://photos.app.goo.gl/omzlzICdqPt6Tgzx2]
2. I will work on that will get back to you if you like the idea
3. I will generate an new one when setting up
4. Can you maybe if you have time explain me how?
5. I will clear that up and make it orginized.
6. I will comment it the right way.
7. How do you mean?

Thanks a lot for your time :D
And please let me know what you think.

**Comment by matteocargnelutti** [comment]
Hi Filoor,

No worries :) !
Good job with the interfacing with Tasker.

1. 
2.
3. In that case, the api key field should be service-specific. (for example : tasker_api_key), as the app could connect to different services. Hence comes the problem of those third parties : I'd prefer that Jean-Pierre stayed an open-hardware / open-software project, hence it would be great to only use third parties services that share those values.
So, I think third-parties apps should be added one by one to the main project, if it brings added value to it. But nothing stops you from using whatever third party api in your fork of Jean-Pierre of course :) !

4. From my understanding, the three method you added do the same thing as the three method they are copied from, but shortcuts the authentication system by using an api_key as a GET parameter. Why do you need to do that ?

5.
6.  Great :) ! It's mostly missing descriptions in the methods' headers.

7. Unit testing is a software development process in which you write code whose purpose it to "test" your program. It executes parts of your program, expecting a given result, and if the . See the tests folder for examples.

Have a nice day,
Matteo.

**Comment by matteocargnelutti** [comment]
Oh, maybe i've just understood what you want to do : 
You want to have a Jean-Pierre API key for other apps to interact with, not the other way around ?
In that case, the best way would be to change the authentication process entirely, instead of multiplying the methods with alternate authentication access.
Sorry if that's the case and I've just understood.
Have a nice day,
Matteo.

**Pull request closed without merging**
